### ISSUE TITLE
about DHG dataset

### ISSUE THREAD

**Issue by weiyutao886** [multimodallearning/hand-gesture-posture-position#2]
I can't find the DHG dataset. Can you provide this dataset and its dataloader? Thank you

**Comment by weiyutao886** [comment]
It's better to have its data process

**Comment by weiyutao886** [comment]
i got this dataset

**Comment by weiyutao886** [comment]
Hello, I'm very interested in your data on DHG dataset, but I don't quite understand the leave one subject out cross validation strategy mentioned in this dataset. Can you share the tags of your training and testing, as well as the data loader and process mentioned above.

**Comment by alexbgl** [comment]
Hello,
thanks again for your interest and sorry for the late reply.
I just uploaded scripts for preprocessing, training, and testing on DHG.
Leave-one-out CV means that we train our model 20 times. In the first run, we train on subjects 2-20 and validate on subject 1. In the second run, we validate on subject 2 and use subjects 1, 3-20 for training. And so on... The final score is the average accuracy over all runs/subjects.

Hope that helps and let me know if you have any further questions.
