### ISSUE TITLE
DHG14-28数据集下载链接失效了，能否提供其他有效的下载链接呢？

### ISSUE THREAD

**Issue by yunfan258** [multimodallearning/hand-gesture-posture-position#4]
http://www-rech.telecom-lille.fr/DHGdataset/
DHG14-28数据集的这个官网链接打不开，能否提供云盘下载链接呢？或者其他有效链接

**Comment by yunfan258** [comment]
> http://www-rech.telecom-lille.fr/DHGdataset/ DHG14-28数据集的这个官网链接打不开，能否提供云盘下载链接呢？或者其他有效链接

又可以打开了

**Comment by zhou13037470950** [comment]
你好，有现存的DHG14/28的数据集吗，包含骨骼数据的，能否分享一下，谢谢啦！
